### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by dlangille**
`recursive = zfs`

should be:

`recursive = yes`

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
Personally, I agree that recursive=yes is a better default. But this isn't a typo, it's two different methods of recursion. Recursive=zfs is more efficient, recursive=yes is more predictable (recursive=zfs won't take a monthly of a newly created child dataset until the parent also needs one; recursive=yes takes one right away).

I don't have much dog in the fight over which to default to, but a change needs discussion and consensus.

**Comment by dlangille** [comment]
Sorry, I thought it was a typo.  I was sure it was because I didn't find a reference to `zfs` recursion.

**Comment by dlangille** [comment]
Is this missing from the docs? I see `atomic` mentioned at https://github.com/jimsalterjrs/sanoid/blob/master/sanoid.conf#L31 but that wasn't enough to tell me `zfs` is different from `yes`

**Comment by phreaker0** [comment]
no typo :-)
documentation pr's welcome :-)

**Comment by dlangille** [comment]
Here I was, all ready to document if I could get questions answered....

**Comment by phreaker0** [comment]
@dlangille sry. I thought we do the documentation update in a new PR but we can recycle this one too.

> Is this missing from the docs? I see `atomic` mentioned at https://github.com/jimsalterjrs/sanoid/blob/master/sanoid.conf#L31 but that wasn't enough to tell me `zfs` is different from `yes`

yes, that's all of the current documentation for recursive = zfs. Basically this runs zfs snapshot with the '-r' flag so zfs will recursively take a snapshot of the whole dataset tree which is consistent.

**Comment by dlangille** [comment]
I added a new commit, and it involves some assumptions about `recursive = yes`, which I could not substantiate when reading the code. i.e. I could not see where that option does not use `-r`.

**Pull request closed without merging**
