### PR TITLE
fixed a regression which causes perl warnings

### PR DESCRIPTION
**Pull request by phreaker0**
Caused by  #267

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
OK this fixed the warnings on my end. I did some minor testing and normal operation of sanoid --cron and various syncoid operations seem to work fine on my own workstation; do you think we should go ahead and push as v2.0.0 and expect a possible 2.0.1 necessary soon, or do you think we should give it some time for more testing?

**Comment by phreaker0** [comment]
I would wait a week for the 2.0.0 release, this should give some time for testing as there were much code changes merged together. I will roll out the latest master on some of my machines and report/fix any errors I encounter.

**Comment by jimsalterjrs** [comment]
I'm'a go let the brave people on Reddit know there's a pre-release which has passed basic initial tests up for volunteer testing while we're at it.

**Comment by phreaker0** [comment]
good idea!

**Comment by phreaker0** [comment]
@jimsalterjrs I rolled out the master version + path patch (#270) on all my productions machines (ubuntu 18.04, debian 8 and debian 9) five days ago. I didn't have any problems so far. Since yesterday I also rolled out the changes from #216 to all machines.
Releasing the current master as 2.0.0 gets green light from me.

**Comment by jimsalterjrs** [comment]
OK, I've had it running on a few machines and haven't seen any issues yet either. Releasing now, then I'm going to merge the other stuff you've approved immediately afterwards.

**Pull request merged**
