### PR TITLE
[Regression fix] Change of DST handling

### PR DESCRIPTION
**Pull request by shodanshok**
As discovered today, the new DST handling approach (which I authored here https://github.com/jimsalterjrs/sanoid/pull/362) has a serious problem: the first day of a month, the variable `preferredtime[3]` become `0`, causing an exception. See here for an example of the problem: https://github.com/jimsalterjrs/sanoid/issues/394

I issued an immediate fix here: https://github.com/shodanshok/sanoid/commit/ada4240afa0a33bf26918f08ac394b5194b1b80c

However, I am re-evalating the base approach. The right solution would be to use Perl `Date::Time` class to handle date/time, but this requires an external Perl module (increasing the dependencies list)

So, in order to fix the problem without requiring new dependencies *and* in the simpler manner possible, I propose this PR. The only downside compared to current code is an additional `daily` snapshot taken at DST change.

If you want no additional snapshot, the two methods can be combined; for example:

```
412,413c412,417
<                                               $preferredtime[3] -= 1; # preferred time is later today - so look at yesterday's
<                                               $lastpreferred = timelocal(@preferredtime);
---
>                                               if ($preferredtime[3] > 1) {
>                                                       $preferredtime[3] -= 1; # preferred time is later today - so look at yesterday's
>                                                       $lastpreferred = timelocal(@preferredtime);
>                                               } else {
>                                                       $lastpreferred -= 60*60*24; # workaround for first day of month
>                                                       if ($lastpreferred > time()) {$lastpreferred -= 60*60} # skip an hour due to unhandled DST crossing
>                                               }
```

Anyway, the current patch should be reverted to avoid *no* snapshots taken on the first day of each month. Sorry for introducing the problem.

### CODE REVIEW

**Comment by shodanshok** [comment]
@jimsalterjrs  @phreaker0  Please review the proposed PR. Thanks.

**Comment by shodanshok** [comment]
@jimsalterjrs @phreaker0 any chances to review the patch? The issue seems quite important, and a fix is required. Thanks.

**Comment by shodanshok** [comment]
@phreaker0 Thanks for reviewing the patch. It is true, a single duplicate daily snapshot is to be expected. It should be avoided with additional checks, but I am afraid to complicate the snapshot-decision code. I would argue that a single duplicate daily snapshot (which somewhat compensate the *missing* hourly snapshot due to DST crossing) is a very small price to pay for solving the original problem (dozens of duplicate snapshot) in the simple possible manner.
@jimsalterjrs any clue?

**Comment by phreaker0** [comment]
@shodanshok @jimsalterjrs i made a pr (#406) with an alternative which solves the problem technically correct (no missing or duplicate snapshots) but by keeping the working/complex code.

**Comment by shodanshok** [comment]
@phreaker0 well done! To be honest, due to my obsession with simplicity, I continue to *slightly* like more the simpler approach proposed here (which is a one-line change vs the original implementation). After all, one can always use `TZ=UTC` and avoid the missing/duplicate snapshot. However, it is very nice to have an alternative (and more correct) implementation to evaluate; thanks.
@jimsalterjrs its your choice; I'll be happy with any one of the proposed changes.

**Comment by gdevenyi** [comment]
I wrote up a small proposal at #409 about using the DateTime module to handle comparing snapshots using standardized comparions and reproducible checks. Please take a look.

**Comment by shodanshok** [comment]
@jimsalterjrs any thoughts on the matter? We should really fix the git master. While I like the simpler approach detailed here, I would be happy with *any* working patch. Thanks.

**Pull request closed without merging**
