### PR TITLE
WIP: reset resume state

### PR DESCRIPTION
**Pull request by phreaker0**
Relates to #304. This is the rebased attempt from some time ago, it detects a partial resume state and resets it so it will work but I'm not happy because it hides the command output. I need to find a way to:

- run the sync command like system()
- but with support for capturing the stderr output
- while the stdout and stderr are still printed to the user 

So more error types can be captured and handled properly (like invalid resume state, ...)

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
Hey @phreaker0 I just had a thought about this. While we do still need to manage broken resume states in syncoid... how hard is it to *check* for a resume state? Should we look at having Sanoid refuse to prune a snapshot with an associated resume state? Is that practical? If so, it would eliminate 95%+ of the actual real-world problems associated with this issue.

Honestly I kinda wonder if we shouldn't be reporting this upstream; zfs itself should probably refuse to destroy a snapshot with an associated resume state without use of a -F flag, much like it won't destroy a snapshot associated with a clone without one.

**Comment by phreaker0** [comment]
@jimsalterjrs 
The resume state is only saved on the destination dataset, so a sanoid run on the src dataset/snapshot unfortunately can't detect snapshots which are part of an partial replication.

**Comment by jimsalterjrs** [comment]
Is this perhaps worth defining replication partners in sanoid.conf, 
allowing a check of the replication partners for existing resume states? Or 
is checking for resume states too heavy an operation?

**Comment by phreaker0** [comment]
This seems to be more complicated than a proper solution which should work without configuration and hopefully in all cases :-)

**Comment by jimsalterjrs** [comment]
@phreaker0 have you done any testing on this commit yet?

**Comment by phreaker0** [comment]
@jimsalterjrs yes it works. I can get the error output from the zfs command while it's also directly forwarded to the terminal. But the only caveat is the need of an additional perl package (Captrue::Tiny). I still need to rewrite it to be nicer but like this I can catch other errors too easily and can handle them automatically instead of aborting if possible.

**Comment by jimsalterjrs** [comment]
Freaking sweet; really looking forward to being able to turn off --no-resume on my automated cron jobs!

**Comment by phreaker0** [comment]
You really wanted that feature :-D I will push some documentation updates regarding this later.

**Pull request merged**
