### PR TITLE
Added in --sendoptions=OPTIONS and --recvoptions=OPTIONS to inject OP…

### PR DESCRIPTION
**Pull request by clinta**
This is a cleaned up rebase of @mattaw's PR #273.

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
@phreaker0 moar rebase

**Comment by clinta** [comment]
@jimsalterjrs @phreaker0 rebased again.

**Comment by mattaw** [comment]
Thankyou so much, I got buried by the end of our semester and was planning to tackle it again near Christmas.

**Comment by jimsalterjrs** [comment]
Still have conflicts that need to be resolved.

**Comment by TerraTech** [comment]
I believe this needs a bit more fine tuning where some options need to be masked depending on the dataset being transferred.

Case in point is applying:  --recvoptions="-o canmount=noauto"
which will work fine for filesystem types, but will throw an error if a volume type is being processed.

I'm thinking that a possible solution is to extend the options to provide specificity, e.g.
- --recvoptions=
- --recvoptions-filesystem=
- --recvoptions-volume=

or if you don't want to balloon the number of options, then a additive building parser can be done:
- --recvoptions="<common to all dataset types>"
- --recvoptions=":filesystem:-o canmount=noauto"

where the applied options is scoped to the embedded ```:identifier:```  (I'm open to alternative delimiters)

The internal hash would be a HOL:
```perl
%recvoptions = (
  common => (...),
  filesystem => (...),
  volume => (...)
);
```

Then the correct options could be applied via introspection:
```perl
my $fstype = getzfsvalue($sourcehost,$sourcefs,$sourceisroot,'type');
if ($fstype eq 'volume') {
  $receiveextraargs = join(' ', @recvoptions{common,volume});
}
elseif ($fstype eq 'filesystem') {
  $receiveextraargs = join(' ', @recvoptions{common,filesystem});
}
else {
  $receiveextraargs = join(' ', $recvoptions{common});
}
```

**Comment by clinta** [comment]
@jimsalterjrs @phreaker0

Would it be possible to get this reviewed and merged before it falls out of sync and needs another rebase?

**Comment by efinley1272** [comment]
+100

**Comment by mailinglists35** [comment]
for my use case of "send -Lc" and "receive -vu" it does not break resumable replication

**Comment by mailinglists35** [comment]
I see it correctly gets a resume token and if interrupted it correctly picks up the token and completes the send.

**Pull request merged**
