### PR TITLE
preserve taking snapshots order always from yearly to frequently && pre/post snapshot script calls should be also dumped in --readonly mode

### PR DESCRIPTION
**Pull request by matveevandrey**

### CODE REVIEW

**Comment by matveevandrey** [comment]
As I wrote in my commit this double loop is ugly but the simplest way to achieve required with minimal changes. It **can not**  be done "directly iterate over the known types" because the key should also be found to get corresponding values

**Comment by phreaker0** [comment]
The key always exists for all the known types because they are defined in the sanoid.defaults.conf file which shouldn't be changed by the user and is part of the installation.

**Comment by matveevandrey** [comment]
done

**Comment by phreaker0** [comment]
thank you! I still need to try it out.

**Pull request merged**
