### PR TITLE
Skip parent

### LINKED ISSUE #231: Feature request: "process_children_only" for syncoid
sanoid has option `process_children_only` to skip the parent when doing a recursive operation.  It would be very helpful if syncoid had a corresponding option.

Example of use: I have several machines which are doing recursive syncs to a backup server, e.g.

```
syncoid --quiet -r zfs/vm root@storage1:storage1/ganeti
```

Every time this runs I get:

```
CRITICAL ERROR: Target storage1/ganeti exists but has no snapshots matching with zfs/vm!
                Replication to target would require destroying existing
                target. Cowardly refusing to destroy your existing target.
```

I do not want to sync the top-level `zfs/vm -> storage1/ganeti` because there are multiple hosts dumping into the same target tree; and I don't want to have a separate tree for each source host, because I could use syncoid to move VMs between hosts.

### PR DESCRIPTION
**Pull request by phreaker0**
New option "--skip-parent" for skipping the parent dataset from recursive replication.

Fixes #231

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
Resolve conflicts please?

**Comment by phreaker0** [comment]
done

**Comment by jimsalterjrs** [comment]
@phreaker0, is there a good way to contact you off-list? I've got a couple things I'd like to run by you. Email / twitter / something; I was going to send you a PM here and discovered, oh hey, there _are_ no Github PMs =)

**Comment by phreaker0** [comment]
@jimsalterjrs i submitted my private mail address throug your contact form here: http://jrs-s.net/contact/

**Comment by jimsalterjrs** [comment]
Thanks! Mail is in your box.

**Pull request merged**
