### PR TITLE
special char fixes

### LINKED ISSUE #40: syncoid error with dataset containing spaces in recursive mode
When trying to sync a child dataset containing spaces, syncoid fails as the space is not being escaped.

Steps to reproduce:
1) zfs create pool/test
2) zfs create "pool/test/Hello World"
3) syncoid -r pool/test remote_user@remotehost:pool/test

Output:
root@hostname:~# syncoid -r data5tb/test root@hostname2:data5tb_backup/test
Sending incremental data5tb/test@syncoid_hostname_2016-06-05:10:09:53 ... syncoid_hostname_2016-06-05:10:11:32 (~ 4 KB):
1.52KiB 0:00:00 [5.38KiB/s] [==================================================================>                                                                                                              ] 38%  
cannot open 'data5tb/test/Hello': dataset does not exist
cannot open 'World': dataset does not exist
usage:
        snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
CRITICAL ERROR:  /usr/bin/sudo /sbin/zfs snapshot data5tb/test/Hello World@syncoid_hostname_2016-06-05:10:11:41
 failed: 512 at /usr/local/bin/syncoid line 697.

### PR DESCRIPTION
**Pull request by phreaker0**
This patches will escape all filesystem names, snapshot names and remote ssh commands as necessary to support all the characters which are allowed in ZFS to be used/supported for syncoid.
Furthermore several regular expression were adapted to ignore any meta characters in filesystem/snapshot names.

Fixes #40

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
Oh wait; you didn't bother calling escapeshellparam() on the second one because you know it's a syncoid-generated snap and therefore should not have any weird characters in it, right?

**Comment by jimsalterjrs** [comment]
... except it'll still happen if our second snap ISN'T a syncoid snap, ie if we've invoked --no-sync-snap, it looks like. Going to explicitly test this now.

**Comment by jimsalterjrs** [comment]
There are some other problems to figure out before we can move on from this to the resumable send/receive. The calls to escapeshellparam() fix problems with spaces in dataset names, but they don't fix problems with spaces in _snapshot_ names:

```
root@bittybox:/usr/local/bin# zfs list -rt snap data/test
NAME            USED  AVAIL  REFER  MOUNTPOINT
data/test@1       0B      -   192K  -
data/test@1 2     0B      -   192K  -
root@bittybox:/usr/local/bin# syncoid --no-sync-snap data/test data/test2 --debug
DEBUG: SSHCMD: /usr/bin/ssh    
DEBUG: checking availability of /usr/bin/lzop on source...
DEBUG: checking availability of /usr/bin/lzop on target...
DEBUG: checking availability of /usr/bin/lzop on local machine...
DEBUG: checking availability of /usr/bin/mbuffer on source...
DEBUG: checking availability of /usr/bin/mbuffer on target...
DEBUG: checking availability of /usr/bin/pv on local machine...
DEBUG: syncing source data/test to target data/test2.
DEBUG: checking to see if data/test2 on  is already in zfs receive using  /bin/ps -Ao args= ...
DEBUG: checking to see if target filesystem exists using "  /sbin/zfs get -H name 'data/test2' 2>&1 |"...
DEBUG: getting list of snapshots on data/test using   /sbin/zfs get -Hpd 1 -t snapshot guid,creation 'data/test' |...
Use of uninitialized value in numeric comparison (<=>) at /usr/local/bin/syncoid line 624.
NEWEST SNAPSHOT: data/test@1 2	creation	1524664384	-
DEBUG: target data/test2 does not exist.  Finding oldest available snapshot on source data/test ...
Use of uninitialized value in numeric comparison (<=>) at /usr/local/bin/syncoid line 610.
Use of uninitialized value in numeric comparison (<=>) at /usr/local/bin/syncoid line 610.
DEBUG: getting estimated transfer size from source  using "  /sbin/zfs send -nP 'data/test@data/test@1 2	guid	63237738495259347	-' 2>&1 |"...
DEBUG: sendsize = 0
INFO: Sending oldest full snapshot data/test@data/test@1 2	guid	63237738495259347	- (~ UNKNOWN) to new target filesystem:
DEBUG:  /sbin/zfs send 'data/test'@'data/test@1 2	guid	63237738495259347	-' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/pv -s 0 |  /sbin/zfs receive -F 'data/test2'
DEBUG: checking to see if data/test2 on  is already in zfs receive using  /bin/ps -Ao args= ...
WARNING: could not send data/test@data/test@1 2	guid	63237738495259347	-: does not exist
0.00 B 0:00:00 [0.00 B/s] [<=>                                                                                                                                                                                ]
cannot receive: failed to read from stream
CRITICAL ERROR:  /sbin/zfs send 'data/test'@'data/test@1 2	guid	63237738495259347	-' | /usr/bin/mbuffer  -q -s 128k -m 16M 2>/dev/null | /usr/bin/pv -s 0 |  /sbin/zfs receive -F 'data/test2' failed: 256 at /usr/local/bin/syncoid line 245.
```

**Comment by phreaker0** [comment]
Good catch! I will look into it, thanks for testing.

**Comment by jimsalterjrs** [comment]
No, thank you for doing the work! =)

**Comment by phreaker0** [comment]
@jimsalterjrs 
got it, on top of the missing escapes for the snapshot target of incremental sends, the parsing of the snapshot name failed in case of white space characters.
I linked the new PR.

**Pull request merged**
