### PR TITLE
Add '--no-privilege-elevation' option to bypass root check.

### PR DESCRIPTION
**Pull request by lopsided98**
This PR is designed to implement #139. It adds a `--no-privilege-elevation` option that bypasses the root check on both the source and destination. If you want, I can add separate control of the source and destination checks, or rename the option to something else.

### CODE REVIEW

**Comment by UltraPhil** [comment]
I would suggest `--no-privilege-elevation` to keep the same spirit as the others "no-something" flags, since it inhibits a default behavior.

**Comment by lopsided98** [comment]
That sounds good to me. I updated the PR.

**Comment by jimsalterjrs** [comment]
Hi @lopsided98 - apologies, but you've got conflicts in syncoid since I merged @LordAro 's POD work. Can you review and resolve the conflicts, please?

**Comment by lopsided98** [comment]
I've fixed the conflicts.

**Comment by kapsel** [comment]
@jimsalterjrs: Any chance we could get this merged? Works perfect for me!

**Comment by lopsided98** [comment]
Can this be merged?

**Comment by jimsalterjrs** [comment]
Sigh... needs rebase due to me merging out of order again. I didn't realize I had sorted new-on-top instead of old-on-top in the merge tab on github :(

**Comment by lopsided98** [comment]
I fixed the conflicts.

**Comment by lopsided98** [comment]
Thanks!

**Pull request merged**
