### PR TITLE
preserve recordsize

### PR DESCRIPTION
**Pull request by phreaker0**
Implemented option to preserve record sizes on initial sends.

### CODE REVIEW

**Comment by phreaker0** [comment]
sry for the whitespace noise

**Comment by jimsalterjrs** [comment]
Is this on by default, or only if specified?

**Comment by jimsalterjrs** [comment]
looks like will need rebase also due to other PRs accepted =\

**Comment by phreaker0** [comment]
rebased.
It's only used if activated with the --preserve-recordsize flag.

**Comment by tonymmm1** [comment]
Can you add a function to check if dataset is zvol otherwise it will error out and skip.

**Comment by phreaker0** [comment]
@tonymmm1 Will do later, thx

**Comment by jimsalterjrs** [comment]
blargh, needs rebase again. sorry. I'd hang off on this until tomorrow probably, I'm chewing my way through a ton of PRs so I might end up invalidating it again before I'm done.

**Comment by phreaker0** [comment]
@jimsalterjrs rebased

**Comment by jimsalterjrs** [comment]
Hey Christoph, we've got a couple more that you'd previously labeled ready for merge up for rebase. After those get done, we should do some dogfooding to make sure everything's working properly, then roll up a new release.

Would you be willing to write up the changelist for that again?

**Comment by phreaker0** [comment]
@jimsalterjrs sure, will do it over the next days, nice that things are moving again :-)

**Pull request merged**
