### PR TITLE
Debian packaging

### PR DESCRIPTION
**Pull request by rlaager**
I got to thinking about packaging sanoid again. I see some work has been done in that direction. Here is a series of fixes, plus a TODO file outline additional work that needs to be done.

I've been using sanoid for some time, so I'd be interested in packaging it for Debian. Are you still agreeable to that?

Note that the best practice is to have the packaging in a separate repository from upstream. I'm submitting this here so that the effort isn't wasted if someone else picks this up. But if I'm doing it, the packaging will move.

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
I can't believe I missed this. @rlaager , yes, I'd love to have sanoid in the Debian repos. There are conflicts now with some other patches I've accepted in the meantime, would you review please?

I don't have any issue with you doing packaging in a separate repo btw.

**Comment by rlaager** [comment]
Unfortunately, this is not something I currently have time to work on. If anyone else is interested, they should proceed and not wait on me.

**Comment by jimsalterjrs** [comment]
@phreaker0 was this superseded by your debian packaging PRs, or does this need to be rebased once I've worked my way through the merge spree today?

**Comment by phreaker0** [comment]
@jimsalterjrs this needs a rebase, my changes were only minor and doesn't fix the problems this one addresses

**Comment by jimsalterjrs** [comment]
@phreaker0 if you're interested in working on this, I'd love the help. I never really got very solid on Debian packaging myself.

**Comment by mjturner** [comment]
I'm quite familiar with Debian packaging (I'm a developer on hiatus) so would love to chip in and help. Perhaps as a first step I can rebase @rlaager 's pull request?

**Comment by jimsalterjrs** [comment]
Any and all help gratefully accepted on this. 

On 2019-03-26 17:18,
Michael-John Turner wrote: 

> I'm quite familiar with Debian packaging
(I'm a developer on hiatus) so would love to chip in and help. Perhaps
as a first step I can rebase @rlaager [1] 's pull request? 
> 
> --
>
You are receiving this because you were mentioned.
> Reply to this email
directly, view it on GitHub [2], or mute the thread [3].




Links:
------
[1] https://github.com/rlaager
[2]
https://github.com/jimsalterjrs/sanoid/pull/170#issuecomment-476856772
[3]

**Comment by tomposmiko** [comment]
Any news on this?
It would be so great to get it merged.

**Comment by peterNordin** [comment]
@phreaker0 I have re-based the branch behind this pull request, and opened a new pull request since I can not push to this one.

**Comment by rlaager** [comment]
Closing in favor of #446

**Pull request closed without merging**
