### PR TITLE
support monitor time period suffixes

### PR DESCRIPTION
**Pull request by phreaker0**

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
@phreaker0 do you see any reason NOT to make the regex case-insensitive in your convert subroutine, so that 5w and 5W both refer to 5 weeks?

I'd like to get sanoid.defaults.conf to use explicit values (ie 5w instead of 5, 30h instead of 30, etc) once we've gotten some testing on this and are confident of it.

**Comment by phreaker0** [comment]
@jimsalterjrs I actually had it that way until I came across the **M**onth and **m**inute issue :-) we could:
- have it case insensitive for all other suffixes
- use "mi" for minutes or "mo" for months
- leave it case sensitive

what do you prefer?

**Comment by jimsalterjrs** [comment]
Oooh, excellent point. I'm in favor of (m)inutes and (M)onths, everything else can be case insensitive. Or just not having months be an option at all; I don't really believe there's much value in months as an option in this context. The only place months or weeks are really meaningful IMO is in taking monthlies or taking weeklies in the first place, and specifying how many to keep; but that's taken care of with "how many we keep" and therefore doesn't need a unit specified.

**Comment by redmop** [comment]
I believe it should be all cast sensitive or none of it should be. For the end user.
Znapzend uses the following:
second|sec|s
minute|min
hour|h
day|d
week|w
month|mon|m
year|y

**Comment by lckarssen** [comment]
Would it make sense to follow the conventions of the variables of the `date` tool? There, `%M` is for minute, `%m` is for month.

**Comment by jimsalterjrs** [comment]
If simply dropping the month unit resolves the problem, I say we drop the month unit and resolve the problem that way. I just don't see any actual use for that unit, since "monthly = 3" captures three monthly snapshots without the need to either specify units or try to convert into days.

**Pull request merged**
