### PR TITLE
Changed (and simplified) DST handling

### PR DESCRIPTION
**Pull request by shodanshok**
See https://github.com/jimsalterjrs/sanoid/issues/155 for background information.

This patch streamlines `sanoid` DST handling, reverting the "snapshot suffix" behavior introduced with https://github.com/jimsalterjrs/sanoid/pull/175. 

The only downside of this approach is the missing of a single hourly snapshot (with duplicate 02:00:00 time). To avoid that, one should use UTC time (as clearly documented).

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
@shodanshok rebase needed please, sorry!

**Comment by shodanshok** [comment]
@jimsalterjrs @phreaker0 I rebased my path, please give it a look.

**Comment by shodanshok** [comment]
@phreaker0 Interesting, on a CentOS 7 VM I have *no* duplicate daily snapshot:

```
sanoid-test-2@autosnap_2017-10-28_00:00:00_daily
sanoid-test-2@autosnap_2017-10-28_00:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_00:00:00_monthly
sanoid-test-2@autosnap_2017-10-28_01:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_02:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_03:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_04:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_05:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_06:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_07:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_08:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_09:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_10:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_11:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_12:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_13:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_14:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_15:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_16:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_17:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_18:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_19:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_20:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_21:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_22:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_23:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_00:00:00_daily
sanoid-test-2@autosnap_2017-10-29_00:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_01:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_02:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_03:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_04:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_05:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_06:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_07:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_08:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_09:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_10:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_11:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_12:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_13:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_14:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_15:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_16:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_17:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_18:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_19:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_20:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_21:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_22:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_23:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_00:00:00_daily
sanoid-test-2@autosnap_2017-10-30_00:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_01:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_02:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_03:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_04:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_05:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_06:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_07:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_08:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_09:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_10:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_11:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_12:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_13:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_14:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_15:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_16:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_17:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_18:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_19:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_20:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_21:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_22:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_23:00:00_hourly
```

I had to spin up a FreeBSD VM to check. Do you have any clue?

**Comment by shodanshok** [comment]
@phreaker0 I just installed a FreeBSD 11.2 VM (with perl 5.28) and I have *no* strange daily snapshots:

```
root@freebsd:~/sanoid/tests/2_dst_handling # uname -a
FreeBSD freebsd 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 04:32:14 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

root@freebsd:~/sanoid/tests/2_dst_handling # perl -v

This is perl 5, version 28, subversion 1 (v5.28.1) built for amd64-freebsd-thread-multi
```

```
sanoid-test-2@autosnap_2017-10-28_00:00:00_daily
sanoid-test-2@autosnap_2017-10-28_00:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_00:00:00_monthly
sanoid-test-2@autosnap_2017-10-28_01:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_02:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_03:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_04:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_05:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_06:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_07:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_08:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_09:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_10:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_11:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_12:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_13:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_14:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_15:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_16:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_17:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_18:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_19:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_20:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_21:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_22:00:00_hourly
sanoid-test-2@autosnap_2017-10-28_23:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_00:00:00_daily
sanoid-test-2@autosnap_2017-10-29_00:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_01:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_02:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_03:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_04:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_05:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_06:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_07:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_08:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_09:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_10:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_11:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_12:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_13:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_14:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_15:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_16:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_17:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_18:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_19:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_20:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_21:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_22:00:00_hourly
sanoid-test-2@autosnap_2017-10-29_23:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_00:00:00_daily
sanoid-test-2@autosnap_2017-10-30_00:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_01:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_02:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_03:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_04:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_05:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_06:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_07:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_08:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_09:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_10:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_11:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_12:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_13:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_14:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_15:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_16:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_17:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_18:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_19:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_20:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_21:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_22:00:00_hourly
sanoid-test-2@autosnap_2017-10-30_23:00:00_hourly
```

**Comment by phreaker0** [comment]
@shodanshok did you use a one minute interval? By default the test uses 900 seconds / 15 minute interval.

**Comment by shodanshok** [comment]
Ah ok, with a 60s interval I confirm to see the "wrong" snapshot on both Linux and FreeBDS. But I ask: is it really a problem? No snapshots are duplicate, rather a single one has 1 minute earlier timestamp. We don't lose anything, as a `sanoid-test-2@autosnap_2017-10-30_00:00:00_hourly` exists.

It seems a reasonable tradeoff to me, with a much simpler approach to DST. Am I missing something?

**Comment by shodanshok** [comment]
@phreaker0 Hi, did you have a chance to check my last update on the matter? Any thoughts?

**Comment by phreaker0** [comment]
@shodanshok didn't had time too look into the issue yet.

**Comment by phreaker0** [comment]
Sorry, I looked into it and It's not an error but expected behavior, because the tests starts at the start of the day. Daily snapshot get's created because there is no other yet. I will adapt the test case after this is merged.

**Comment by jimsalterjrs** [comment]
Thank you @shodanshok :)

**Pull request merged**
