### PR TITLE
Fixed Typo in arguments.

### LINKED ISSUE #480: syncoid was broke with probable typo for zfs list
Copy -n- paste of my comment below. 

> This broke zfs list with and invalid argument of "A-Hpd" I believe it should be "-Hpd". There no "A" parameter for zfs list.

Removing the errant A from the command line arguments returns syncoid back to the land of functionality.

Eh, made a PR for it... :)

Link to comment and broke commit / code: https://github.com/jimsalterjrs/sanoid/commit/28ef311ba5b337a9e0283088825cd92f0dfbe01b#r36857988

### PR DESCRIPTION
**Pull request by croadfeldt**
Removed errant A in zfs list command line arguments.

Fixes #480

### CODE REVIEW

**Comment by phreaker0** [comment]
thx, the A was for debugging/testing the fallback/alternative code for listing the snapshots (solaris support) so I could test it on my linux machine. Seem like I overlooked it in some commit :-(

**Comment by croadfeldt** [comment]
I’ve done that more than once myself... :)

**Comment by phreaker0** [comment]
@jimsalterjrs pls merge this fix asap, a lot of people are complaining already about my typo/debug mistake :-)

**Comment by Will-Moshe** [comment]
@phreaker0 

This bug wouldn't affect Solaris implementations, correct?

**Comment by phreaker0** [comment]
@Will-Moshe correct, the typo was put there so the solaris code is used

**Pull request merged**
