### PR TITLE
added option for using extra identification in the snapshot name for …

### LINKED ISSUE #225: Support for multiple targets
I want to replicate my zpool to three different targets (usb drives).
That means I need to keep three sync states for syncoid to be able to sync against a drive that has not been connected for the last couple of sync runs.
I can see, that syncoid creates snapshots with the name syncoid-<hostname>_<datetime>.
Is it possible to use another label (like disk1, disk2 and disk3 for example) instead of the hostname or append a suffix to the snapshot label?

### PR DESCRIPTION
**Pull request by phreaker0**
…replicating to multiple targets.

Fixes #225

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
Hey Christoph, conflicts with some of your other patches which I've accepted. Resolve please?

**Comment by phreaker0** [comment]
I will wait for merged #233 , as it would conflict again

**Comment by phreaker0** [comment]
I resolved the conflicts and allowed all characters which are supported by zfs snapshots to be used.

**Comment by jimsalterjrs** [comment]
Looks good from here. I assume you've tested?

**Comment by phreaker0** [comment]
Yes, I'm actually using it in production already for remote backup stuff.

**Pull request merged**
